### ISSUE TITLE
html in text device

### ISSUE THREAD

**Issue by papo-o** [domoticz/Reacticz#19]
is there a possibility to interpret the html tags contained in the text devices in order to respect the formatting of the text? (only font and color)
or possibly delete the tags completely and only display the text contained in the device
![2017-11-14 18_04_37-dashboard _ reacticz](https://user-images.githubusercontent.com/25136535/32980574-425051de-cc69-11e7-946e-193d6bf548ef.png)

**Comment by t0mg** [comment]
Fixed by commit 45933fc that allows some HTML formatting in text widgets.

Note that the <font> tag has been deprecated for years and isn't officially supported in HTML5. With the new commit, styling is still forbidden for security reasons. However some tags like <em> and <strong> will allow basic styling of your content.
